Testing branch
rammazzoti2000/Using-Bootstrap pull request #1
Opened 2020-02-09 16:33 UTC by rammazzoti2000

This branch is used for code review.

This project is trying to replicate as much as possible the NewsWeek.com page.
The objectives for this project were to use as many Bootstrap classes as possible to recreate the website mentioned above.
Bootstrap has been used almost for everything: background, font-weight, colors, position, display, grid (rows and col's), margin, padding, height etc.. Except for specific html elements that required extra css styling like colors, font-family and also for hovering the elements.

The website replica contains at the top a navbar splitted in two parts, the header logo on top and  on bottom the nav elements along with the input filled (on the right).

The main header section is made out of three columns (feature stories, top stories and opinion), following on a long variety of different sections dedicated to main news themes like health, tech and science, latest news etc.
In the lat part of the website there is a dedicated section to media sharing and signing up, followed by the simplistic footer.
Thank you for reading.

2020-02-09 17:05 UTC, rammazzoti2000 commented
I know stickler is giving me this wired errors, but everything has been fixed, all the errors is showing I don't see them in my code, I don't know what's happening, if anyone has a suggestion why is this happening, is showing me code I don't have?!

2020-02-09 19:37 UTC, mosesogwo requested changes
### Hi @rammazzoti2000, you have a great project :+1:. Just a few changes are required:

1. Set the background of the navbar so that it doesn't contrast with the background of the logo. You can use a color picker to identify the exact color on the logo background and use that as your nav's background.

2. The social media icons in the footer should be aligned to the left at the same breakpoint where the page switches to a single column. Yours stay on the right and moves to the left at another breakpoint.

3. Regular use of `!important` is bad css practice. Try to avoid them.

4. We can do more with bootstrap classes. The goal of this project is to use them. See comments on your stylesheet and replace all similar stylings with bootstrap classes. I know it may be tedious, but that is the essence of this particular project.

![](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/using_bootstrap/bootstrap_classes_requirement.png)


_**Kindly make these changes and submit another code review request.**_

**Cheers:smile:**

### Status: Changes requested.

2020-02-09 19:37 UTC, mosesogwo commented on style/style.css
> +  padding: 0;
Replace with bootstrap class

2020-02-09 19:37 UTC, mosesogwo commented on style/style.css
> +  text-decoration: none;
Replace all instances of text-decoration-none with bootstrap class .text-decoration-none

2020-02-09 19:37 UTC, mosesogwo commented on style/style.css
> +  font-weight: bold;
Use bootstrap class

2020-02-09 19:37 UTC, mosesogwo commented on style/style.css
> +  float: right;
Use bootstrap class

2020-02-09 19:37 UTC, mosesogwo commented on style/style.css
> +  display: inline-block;
Use bootstrap class

2020-02-09 19:37 UTC, mosesogwo commented on style/style.css
> +  text-align: center;
Use bootstrap class

2020-02-09 19:37 UTC, mosesogwo commented on style/style.css
> +  margin-top: 0;
Use bootstrap class

2020-02-09 19:37 UTC, mosesogwo commented on style/style.css
> +}
Use bootstrap classes

2020-02-09 19:37 UTC, mosesogwo commented on style/style.css
> +  font-weight: bold;
Use bootstrap class

2020-02-09 22:54 UTC, rammazzoti2000 commented on style/style.css
> +  float: right;
isn't ::before selector only available in css? I am just asking since I wouldn't know how to replace that selector with html

2020-02-10 01:48 UTC, nikasulo approved these changes
# Congrats! @rammazzoti2000 
You have done a great job! :rocket: Please merge and keep moving forward

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

2020-02-10 06:52 UTC, merged